//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sem3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eProjectSem3Entities3 : DbContext
    {
        public eProjectSem3Entities3()
            : base("name=eProjectSem3Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<competition> competition { get; set; }
        public virtual DbSet<contact> contact { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<posts> posts { get; set; }
        public virtual DbSet<recipe> recipe { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
